module com.keykiosk {
    requires javafx.controls;
    requires javafx.fxml;
    requires org.controlsfx.controls;
    requires java.sql;
    requires spring.boot;
    requires spring.context;
    requires spring.boot.autoconfigure;
    requires spring.beans;
    requires spring.core;
    requires spring.data.jpa;
    requires jakarta.persistence;
    requires org.hibernate.orm.core;
    requires jakarta.validation;
    requires spring.tx;
    requires javafx.base;
    requires spring.security.crypto;
    requires modelmapper;
    requires java.desktop;
    requires java.mail;
    requires io.reactivex.rxjava3;
    requires static lombok;
    requires com.jfoenix;
    requires spring.security.core;
    requires org.slf4j;
    requires jakarta.annotation;
    requires org.checkerframework.checker.qual;
    requires org.apache.poi.poi;
    requires org.apache.poi.ooxml;
    requires spring.data.commons;
    requires kernel;
    requires layout;

    opens com.keykiosk.Models to spring.core;
    opens com.keykiosk.Models.DTO;
    opens com.keykiosk.Controllers.Components;
    exports com.keykiosk.Models.DTO to modelmapper;
    opens com.keykiosk.Controllers.Admin;
    opens com.keykiosk.Controllers.Authentication;
    opens com.keykiosk.Models.Repository;
    opens com.keykiosk.Models.Entity;
    opens com.keykiosk.Models.EnumType;
    opens com.keykiosk.Services;
    opens com.keykiosk.Views;
    opens com.keykiosk;
    opens com.keykiosk.Util;
    opens com.keykiosk.Validators;
    opens com.keykiosk.Services.Impl;
    opens com.keykiosk.Config;
    opens com.keykiosk.Observer;
    exports com.keykiosk.Observer;
    exports com.keykiosk.Controllers.Components;
    exports com.keykiosk;
    exports com.keykiosk.Controllers.Authentication;
    exports com.keykiosk.Controllers.Admin;
    exports com.keykiosk.Models.Repository;
    exports com.keykiosk.Models.Entity;
    exports com.keykiosk.Models.EnumType;
    exports com.keykiosk.Services;
    exports com.keykiosk.Exception;
    exports com.keykiosk.Views;
    exports com.keykiosk.Services.Impl;
    exports com.keykiosk.Util;
    exports com.keykiosk.Config;
    exports com.keykiosk.Validators;
}